config/routes.rb
Rails.application.routes.draw do
  
  resources :users
  resources :feedbacks
  resources :sessions, only: [:new, :create, :destroy]
  resources :happies
  resources :bills
  resources :plans
  resources :reminds
  resources :memories

  root to: 'static_pages#home'
  match '/about',          to: 'static_pages#about',            via: 'get' 
  match '/calendar',       to: 'static_pages#calendar',         via: 'get'

  match '/signup',         to: 'users#new',                     via: 'get'
  match '/signin',         to: 'sessions#new',                  via: 'get'
  match '/signout',        to: 'sessions#destroy',              via: 'delete'

  match '/finance',        to: 'finance#index',                 via: 'get'
  match '/finance/detail', to: 'finance#detail',                via: 'get'

  match '/times',          to: 'happiness#index',               via: 'get'

  match 'sessions',        to: 'sessions#create',               via: 'post'

end

app/models/bill.rb
class Bill < ActiveRecord::Base
	
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
	
end

app/models/happy.rb
class Happy < ActiveRecord::Base

end

app/models/memory.rb
class Memory < ActiveRecord::Base
	
end

app/models/plan.rb
class Plan < ActiveRecord::Base
	
end

app/models/remind.rb
class Remind < ActiveRecord::Base
	
end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }
	before_create :create_remember_token #方法引用，创建记忆权标
	validates :name, presence: true, #验证存在性
					   length: { maximum: 50 } #验证长度不超过50
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i #邮箱的正则表达式
	validates :email, presence: true,
						format: { with: VALID_EMAIL_REGEX }, #邮箱格式验证
                    uniqueness: { case_sensitive: false } #验证邮箱唯一性，不区分大小写（弱敏感）
    has_secure_password #rails集成函数，用来添加password和password_confirmation 属性，二者都要填写一些内容（非空格），而且要相等；还要定义 authenticate 方法，对比加密后的密码和 password_digest 是否一致，验证用户的身份。以上操作在数据库有 password_digest列后该函数已做到。
  	validates :password, length: { minimum: 6 } #验证密码长度不低于6


#创建记忆权标方法的实现-----------------------------------------------
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.hash(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.hash(User.new_remember_token)
  end

 #-----------------------------------------------------------------
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController

  def index
  	@bills = Bill.all.page(params[:page]) 
  end

  def new
  	@bill = Bill.new
  end

  def show
  	@bill = Bill.find(params[:id])
    respond_to do |format|
      format.html 
      format.json { render :json => { id: @bill.id, createtime: @bill.createtime, sepnd: @bill.spend, detail: @bill.detail }.to_json }
    end

  end

  def create
  	@bill = Bill.new(bill_params)
    respond_to do |format|
      format.html {
      	if @bill.save
          redirect_to bills_path
        else
          render 'new'
        end
      }

      format.json { 
        if @bill.save
          render json: @bill, status: :created
        else
          render json: @bill.errors, status: :unprocessable_entity
        end
      }
    end

  end

  def destroy

  end


  private
	    def bill_params
	      params.require(:bill).permit(:createtime, :spend, :detail)
	    end

end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  def index
  	@plans = Plan.all.page(params[:page]) 
  	# @plans = Plan.all.page({page: @page, per_page: 20}) 
  end

  def new
  	@plan = Plan.new
  end

  def show
    @plan = Plan.find(params[:id])
    respond_to do |format|
      format.html 
      format.json { render :json => { id: @plan.id, title: @plan.title, detail: @plan.detail, createtime: @plan.created_at }.to_json }
    end
  end

  def create
  	@plan = Plan.new(plan_params)
    respond_to do |format|
      format.html {
        if @plan.save
          redirect_to plans_path
        else
          render 'new'
        end
      }

      format.json { 
        if @plan.save
          render json: @plan, status: :created
        else
          render json: @plan.errors, status: :unprocessable_entity
        end
      }
    end

  end
    
  def destroy

  end



	private
	    def plan_params
	      params.require(:plan).permit(:title, :detail)
	    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  	render :layout => false
  end

  def about
  end

  def calendar
  	render :layout => false
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new 
  	@user = User.new
    render :layout => false
  end

  def index
  end

  def show
  	@user = User.find(params[:id])
    respond_to do |format|
      format.html 
      format.json { render :json => { id: @user.id, name: @user.name, email: @user.email, token:@user.remember_token }.to_json }
    end
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      format.html {
        if @user.save
          sign_in @user
          flash[:success] = "Welcome to the INTIMATE!"
          redirect_to @user
        else
          render 'new'
        end
      }

      format.json { 
        if @user.save
          render json: @user, status: :created
        else
          render json: @user.errors, status: :unprocessable_entity
        end
      }
    end
  end

  def update
    respond_to do |format|
      format.html {
        if @user.update_attributes(user_params)
          flash[:success] = "Profile updated"
          redirect_to @user
        else
          render 'edit'
        end
      }

      format.json { 
        if @user.update_attributes(user_params)
          head :no_content, status: :ok
        else
          render json: @user.errors, status: :unprocessable_entity
      end
      }
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

end





=begin

HTTP请求	         URL	        动作	           具名路由	                     作用
GET	            /users	       index	      users_path	           显示所有用户的页面
GET	           /users/1	        show	     user_path(user)	       显示某个用户的页面
GET	          /users/new	    new	         new_user_path	         创建（注册）新用户的页面
POST	        /users	       create	      users_path	              创建新用户
GET	         /users/1/edit	    edit	  edit_user_path(user)	     编辑 id 为 1 的用户页面
PATCH	       /users/1	       update	     user_path(user)	          更新用户信息
DELETE	       /users/1	       destroy	     user_path(user)	            删除用户

=end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/finance_helper.rb
module FinanceHelper
end

app/helpers/happies_helper.rb
module HappiesHelper
end

app/helpers/memories_helper.rb
module MemoriesHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/reminds_helper.rb
module RemindsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
    	remember_token = User.new_remember_token #生成token
    	cookies.permanent[:remember_token] = remember_token #保存token到cookies（cookies[:remember_token] = { value:   remember_token, expires: 20.years.from_now.utc }）；取token：User.find_by(remember_token: remember_token)
    	user.update_attribute(:remember_token, User.hash(remember_token)) #更新user的token，保存记忆权标使用的是 update_attribute 方法，这样可以跳过数据验证更新单个属性。
    	self.current_user = user
 	 end

 	def current_user=(user)
    	@current_user = user
    end

    def current_user?(user)
    	user == current_user
  	end

  	def signed_in?
    	!current_user.nil?
  	end

  	def sign_out
    	current_user.update_attribute(:remember_token,
                                  User.hash(User.new_remember_token))
    	self.current_user = nil
  	 	cookies.delete(:remember_token)
  	end

    def redirect_back_or(default)
      redirect_to(session[:return_to] || default)
      session.delete(:return_to)
    end

    def current_user
    	remember_token = User.hash(cookies[:remember_token])
    	@current_user ||= User.find_by(remember_token: remember_token) #即使页面跳转了，session失效了依然可以获取当前user
  	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/static_pages/about.html.erb
<div class="container">
	<div class="jumbotron">
		<div class="container">
			<h1>关于我们</h1>
			<p>1赵云的经历告诉我们：个人实力再强，若只想着高薪，结果只有一个：有职业，没事业。2张飞的下场告诉我们：要善待员工，若是长期压制奴役，必将得到报复，即使不报复也会导致集体罢工或跳槽。3董卓的下场告诉我们：儿子是不能乱认的，尤其是有前科的，更何况自己是大款，为得家产甘当孙子的都有。</p>
		</div>
	</div>
</div>

app/views/static_pages/calendar.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Intimate</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'fullcalendar.min', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'fullcalendar.print', media: 'print', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'calendar', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script>
    $(document).ready(function() {

      $('#calendar').fullCalendar({
        defaultDate: '2014-09-12', /*new Date(),*/
        editable: true,
        eventLimit: true, // allow "more" link when too many events
        events: [
          ]
      });
      
    });

  </script>
  <style>

    body {
      margin: 40px 10px;
      padding: 0;
      font-family: "Lucida Grande",Helvetica,Arial,Verdana,sans-serif;
      font-size: 14px;
    }

    #calendar {
      max-width: 900px;
      margin: 0 auto;
    }

  </style>
</head>

<body class="grey">

  <section>
    <div class="block center">
      <%= link_to "intimate", current_user, id:"logo" %>
    </div>
    <div id='calendar'></div>
  </section>
  
</body>
</html>

app/views/static_pages/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Intimate</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header class="navbar navbar-fixed-top home-navbar" role="navigation">
	<div class="navbar-inner"> 
		<div class="container">
			<%= link_to "intimate", root_path, id:"logo" %>
    		<nav class= "pull-right">
    			<div class="btn-group">
    				<%= link_to "登录", signin_path, class:"btn, btn-outline-inverse, login-attractive" %>
    				<%= link_to "注册", signup_path, class:"btn, btn-outline-inverse, signup-attractive" %>
    			</div>
			</nav>
      	</div>
  	</div>
</header>

<section class="intimate_origin">
	<div class="container">
		<div class = "row">
      <div class="col-md-10 col-md-offset-1 col-sm-12 col-sm-offset-0 guide-block">
        <h1>INTIMATE,亲密无间的沟通地带</h1>
        <h2>这里有点滴的记录，双方重要的纪念日，各自的近期安排，希望对方的配合。</h2>
      </div>
		</div>
	</div>
</section>

</body>
</html>