config/routes.rb
Rails.application.routes.draw do
  
  resources :users
  resources :feedbacks
  resources :sessions, only: [:new, :create, :destroy]
  resources :happies
  resources :bills
  resources :plans
  resources :reminds
  resources :memories

  root to: 'static_pages#home'
  match '/about',          to: 'static_pages#about',            via: 'get' 
  match '/calendar',       to: 'static_pages#calendar',         via: 'get'

  match '/signup',         to: 'users#new',                     via: 'get'
  match '/signin',         to: 'sessions#new',                  via: 'get'
  match '/signout',        to: 'sessions#destroy',              via: 'delete'

  match '/finance',        to: 'finance#index',                 via: 'get'
  match '/finance/detail', to: 'finance#detail',                via: 'get'

  match '/times',          to: 'happiness#index',               via: 'get'

  match 'sessions',        to: 'sessions#create',               via: 'post'

end

app/models/bill.rb
class Bill < ActiveRecord::Base
	
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
	
end

app/models/happy.rb
class Happy < ActiveRecord::Base

end

app/models/memory.rb
class Memory < ActiveRecord::Base
	
end

app/models/plan.rb
class Plan < ActiveRecord::Base
	
end

app/models/remind.rb
class Remind < ActiveRecord::Base
	
end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }
	before_create :create_remember_token #方法引用，创建记忆权标
	validates :name, presence: true, #验证存在性
					   length: { maximum: 50 } #验证长度不超过50
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i #邮箱的正则表达式
	validates :email, presence: true,
						format: { with: VALID_EMAIL_REGEX }, #邮箱格式验证
                    uniqueness: { case_sensitive: false } #验证邮箱唯一性，不区分大小写（弱敏感）
    has_secure_password #rails集成函数，用来添加password和password_confirmation 属性，二者都要填写一些内容（非空格），而且要相等；还要定义 authenticate 方法，对比加密后的密码和 password_digest 是否一致，验证用户的身份。以上操作在数据库有 password_digest列后该函数已做到。
  	validates :password, length: { minimum: 6 } #验证密码长度不低于6


#创建记忆权标方法的实现-----------------------------------------------
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.hash(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.hash(User.new_remember_token)
  end

 #-----------------------------------------------------------------
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController

  def index
  	@bills = Bill.all.page(params[:page]) 
  end

  def new
  	@bill = Bill.new
  end

  def show
  	@bill = Bill.find(params[:id])
    respond_to do |format|
      format.html 
      format.json { render :json => { id: @bill.id, createtime: @bill.createtime, sepnd: @bill.spend, detail: @bill.detail }.to_json }
    end

  end

  def create
  	@bill = Bill.new(bill_params)
    respond_to do |format|
      format.html {
      	if @bill.save
          redirect_to bills_path
        else
          render 'new'
        end
      }

      format.json { 
        if @bill.save
          render json: @bill, status: :created
        else
          render json: @bill.errors, status: :unprocessable_entity
        end
      }
    end

  end

  def destroy

  end


  private
	    def bill_params
	      params.require(:bill).permit(:createtime, :spend, :detail)
	    end

end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  def index
  	@plans = Plan.all.page(params[:page]) 
  	# @plans = Plan.all.page({page: @page, per_page: 20}) 
  end

  def new
  	@plan = Plan.new
  end

  def show
    @plan = Plan.find(params[:id])
    respond_to do |format|
      format.html 
      format.json { render :json => { id: @plan.id, title: @plan.title, detail: @plan.detail, createtime: @plan.created_at }.to_json }
    end
  end

  def create
  	@plan = Plan.new(plan_params)
    respond_to do |format|
      format.html {
        if @plan.save
          redirect_to plans_path
        else
          render 'new'
        end
      }

      format.json { 
        if @plan.save
          render json: @plan, status: :created
        else
          render json: @plan.errors, status: :unprocessable_entity
        end
      }
    end

  end
    
  def destroy

  end



	private
	    def plan_params
	      params.require(:plan).permit(:title, :detail)
	    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/finance_helper.rb
module FinanceHelper
end

app/helpers/happies_helper.rb
module HappiesHelper
end

app/helpers/memories_helper.rb
module MemoriesHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/reminds_helper.rb
module RemindsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
    	remember_token = User.new_remember_token #生成token
    	cookies.permanent[:remember_token] = remember_token #保存token到cookies（cookies[:remember_token] = { value:   remember_token, expires: 20.years.from_now.utc }）；取token：User.find_by(remember_token: remember_token)
    	user.update_attribute(:remember_token, User.hash(remember_token)) #更新user的token，保存记忆权标使用的是 update_attribute 方法，这样可以跳过数据验证更新单个属性。
    	self.current_user = user
 	 end

 	def current_user=(user)
    	@current_user = user
    end

    def current_user?(user)
    	user == current_user
  	end

  	def signed_in?
    	!current_user.nil?
  	end

  	def sign_out
    	current_user.update_attribute(:remember_token,
                                  User.hash(User.new_remember_token))
    	self.current_user = nil
  	 	cookies.delete(:remember_token)
  	end

    def redirect_back_or(default)
      redirect_to(session[:return_to] || default)
      session.delete(:return_to)
    end

    def current_user
    	remember_token = User.hash(cookies[:remember_token])
    	@current_user ||= User.find_by(remember_token: remember_token) #即使页面跳转了，session失效了依然可以获取当前user
  	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="navbar-inner">
    <div class="container">
      <small>
        <a href="https://github.com/viczy/intimate_web">INTIMATE--github</a>
      </small>
      <nav>
        <ul>
          <li><%= link_to "日历", calendar_path %></li>
          <li><%= link_to "关于", about_path %></li>
          <li><%= link_to "联系我们", new_feedback_path %></li>
          <li><a href="http://viczy.github.io/">作者博客</a></li>
        </ul>
      </nav>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse" role="navigation">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "intimate", current_user, id: "logo" %>
      <nav>
        <ul class="nav navbar-nav pull-right">
          <li><%= link_to "主页", current_user %></li>
          <li><%= link_to "关于", about_path %></li>
          <% if signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                账号 <b class="caret"></b>
              </a> 
              <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1"> 
                <li role="presentation"><%= link_to "个人设置", edit_user_path(current_user) %></li>
                <li role="presentation" class="divider"></li>
                <li role="presentation">
                  <%= link_to "注销", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "登录", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_leftside.html.erb
<div>
    <ul id="leftside" class= <%= tab_index %> >
        <li class="home">
            <%= link_to(current_user) do %>
                <p class="vertical">主页</p>
            <% end %>
        </li>
        <li class="finance">
            <%= link_to(finance_detail_path) do %>
                <p class="vertical">账单</p>
            <% end %>
        </li>
        <li class="plan">
            <%= link_to(plans_path) do %>
                <p class="vertical">计划</p>
            <% end %>
        </li>
        <li class="notice">
            <%= link_to(reminds_path) do %>
                <p class="vertical">通知</p>
            <% end %>
        </li>
        <li class="memory">
            <%= link_to(memories_path) do %>
                <p class="vertical">纪念</p>
            <% end %>
        </li>
        <li class="happiness">
            <%= link_to(times_path) do %>
                <p class="vertical">时光</p>
            <% end %>
        </li>
    </ul>
</div>

<%= javascript_include_tag 'leftside', 'data-turbolinks-track' => true %>

app/views/layouts/_offside.html.erb
<div>
    <ul id="navigation">
        <li class="home"><a href="" title="Home"></a></li>
        <li class="finance"><a href="" title="Finance"></a></li>
        <li class="plan tab_current"><a href="" title="Plan"></a></li>
        <li class="notice"><a href="" title="Notice"></a></li>
        <li class="memory"><a href="" title="Memory"></a></li>
        <li class="happiness"><a href="" title="Happiness"></a></li>
    </ul>
</div>

<script>
    $(function() {
        $('#navigation a').stop().animate({'marginLeft':'-85px'},1000);

        $('#navigation > li').hover(
            function () {
                $('a',$(this)).stop().animate({'marginLeft':'-2px'},200);
            },
            function () {
                $('a',$(this)).stop().animate({'marginLeft':'-85px'},200);
            }
        );
    });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Intimate</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <% if content_for? :for_head %>
  	<%= yield :for_head %>
  <% end %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>
<%= yield %>
<%= render 'layouts/footer' %>

</body>

<% if content_for? :for_script %>
<%= yield :for_script %>
<% end %>

</html>